apiVersion: v1
kind: Service
metadata:
  name: outage-communication-service
spec:
  type: NodePort
  selector:
    app: outage-communication-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007  # You can choose any available port between 30000–32767

